### ISSUE TITLE
pan koza umie c++

### ISSUE THREAD

**Issue by pankoza-pl** [ToWapnoDlaPtakow/dlaczego-batch-to-kasztan#1]
Bo nie używam batcha tylko c++ haha

**Comment by ToWapnoDlaPtakow** [comment]
niezły c++, gdy po rozebraniu twoich wirusów w większości ociekają batchem

**Comment by ToWapnoDlaPtakow** [comment]
haha

**Comment by ToWapnoDlaPtakow** [comment]
czemu uciekasz od odpowiedzi

**Comment by pankoza-pl** [comment]
Pzpl to kasztan

**Comment by ProgramistaZpolski** [comment]
Powody?

**Comment by pankoza-pl** [comment]
Dziwne że konto dopiero terqz masz załóżone

**Comment by ToWapnoDlaPtakow** [comment]
sam jesteś kasztan

**Comment by ToWapnoDlaPtakow** [comment]
> 
> 
> Dziwne że konto dopiero terqz masz załóżone

dopiero się dowiedziałem jakie tu rzeczy się dzieją, więc założyłem konto do walki z batchem i VBS

**Comment by ProgramistaZpolski** [comment]
Ale co bardzo

**Comment by ToWapnoDlaPtakow** [comment]
Bardzo

**Comment by pankoza-pl** [comment]
Batch to kasztan c++ lepszy

**Comment by ProgramistaZpolski** [comment]
PHP najlepszy

**Comment by pankoza-pl** [comment]
Alt pzpla

**Comment by ProgramistaZpolski** [comment]
To nie mój alt

**Comment by ToWapnoDlaPtakow** [comment]
Wszystko >>>>>>>>>>>>>>>>>> Batch, VBS, C++, Delphi :> deal with that

**Comment by pankoza-pl** [comment]
Alt the vision lub pzpla hyba

**Comment by ToWapnoDlaPtakow** [comment]
> 
> 
> Alt the vision lub pzpla hyba

hyba

**Comment by pankoza-pl** [comment]
Kasztanlang najlepszy język

**Comment by ProgramistaZpolski** [comment]
Ja ci tylko powiem że to na 100% nie mój alt

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ToWapnoDlaPtakow** [comment]
No i po chuj łapiesz naszą kulturę? Myślisz że nas tym odgonisz czy udobruchasz czy co?

**Comment by ProgramistaZpolski** [comment]
Wogóle zainstalowałeś PHP na swoim komputerze? Kompilator kasztanlang jest w PHP

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pankoza-pl** [comment]
Alt the vision

**Comment by ToWapnoDlaPtakow** [comment]
skąd wiesz?
Nie jestem niczyim aletem

**Comment by pankoza-pl** [comment]
Ide robić coś w kasztanlangu

**Comment by ProgramistaZpolski** [comment]
Nie spam tym zamykaniem emaila, ok?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ToWapnoDlaPtakow** [comment]
a masz w ogóle php na laptopie, bo compiler do kasztanlang jest w php

**Comment by pankoza-pl** [comment]
Mam php

**Comment by pankoza-pl** [comment]
Emaila mi zaśmiecacie

**Comment by ToWapnoDlaPtakow** [comment]
już widzę jak kodujesz w czymś bez tutoriala/gotowca

**Comment by ToWapnoDlaPtakow** [comment]
plus nie spam maila zamykaniem, bo to nic nie da

**Comment by ProgramistaZpolski** [comment]
a jaką masz wersje? 4.0? 5.0? 6.97?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pankoza-pl** [comment]
To odsubskrybuj

**Comment by ToWapnoDlaPtakow** [comment]
ale on może chce mieć powiadomienia o dyskusji, ale nie chce mieć o twoim niepotrzebnym zamykaniu

**Comment by pankoza-pl** [comment]
Jp3gmd

**Comment by ToWapnoDlaPtakow** [comment]
bardzo śmieszne, odkurzacz się dusi

**Comment by pankoza-pl** [comment]
Pzpl to kasztan

**Comment by ProgramistaZpolski** [comment]
Powody.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ToWapnoDlaPtakow** [comment]
właśnie powody

**Comment by ToWapnoDlaPtakow** [comment]
dlaczego

**Comment by ToWapnoDlaPtakow** [comment]
jak ty nawet z maila nie korzystasz pewno skoro zmieniasz tytuł xDDDDD

**Comment by ProgramistaZpolski** [comment]
Właśnie

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pankoza-pl** [comment]
W c++ umiem lepiej niż ty

**Comment by ToWapnoDlaPtakow** [comment]
mhm, a na prostym zadaniu zamiast go zrobić niszczyłeś system xD

**Comment by pankoza-pl** [comment]
btw https://github.com/pankoza-pl/dlaczego-flash-to-kasztan

**Comment by TheVisionRo-Dak** [comment]
> btw https://github.com/pankoza-pl/dlaczego-flash-to-kasztan

ale napisaliśmy ci odpowiedź ale nie raczyłeś się odnieść xDDDD
