### ISSUE TITLE
twój fork malwaredatabase nic nie wnosi

### ISSUE THREAD

**Issue by pankoza-pl** [ToWapnoDlaPtakow/dlaczego-batch-to-kasztan#4]
to czysty spam

**Comment by lisqu16** [comment]
a twoje repo tymbardziej 
![image](https://user-images.githubusercontent.com/56258709/116653481-96c36900-a987-11eb-9485-f6336784059b.png)

**Comment by pankoza-pl** [comment]
kasztan

**Comment by pankoza-pl** [comment]
btw https://github.com/pankoza-pl/dlaczego-flash-to-kasztan

**Comment by ProgramistaZpolski** [comment]
nawet 1 sekundy researchu do twojego repo nie zrobiłeś...

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
